name: API Tests
on:
  push:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run API Tests
        env:
            TRELLO_API_KEY: ${{secrets.TRELLO_API_KEY}}
            TRELLO_TOKEN: ${{secrets.TRELLO_TOKEN}}
          # ✅ LINUX COMMAND — run tests and log exit code
        run: |
          echo "Running API tests..."
          mvn clean test "-Dcucumber.filter.tags=@api"
          echo "Maven exited with code $?"

      - name: check the target folder
        if: always()
        run: |
          echo "checking the target holder"
          ls -la target/
          if[ -d "target/cucumber-reports"]; then
            echo "folder found"
          else
            echo "not found"
          fi

      - name: upload atificat
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/cucumber-reports/
          retention-days: 7

